name = "sparkmind-web"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"

[env.production]
name = "sparkmind-web"

[env.production.vars]
NODE_ENV = "production"

[env.development]
name = "sparkmind-web-dev"

[env.development.vars]
NODE_ENV = "development" 